import Foundation
import Testing
@testable import HighlightKit

/// Compares the Swift port's token stream against reference fixtures
/// generated by running the actual highlight.js source with a
/// token-capturing emitter (`scratchpad/hljs-ref/gen-fixtures.mjs`).
///
/// A fixture pair is `<lang>/<case>.code.txt` + `<lang>/<case>.tokens.json`.
@Suite("highlight.js fidelity")
struct FidelityTests {
    struct Expected: Decodable {
        struct Token: Decodable {
            let start: Int
            let length: Int
            let scopes: [String]
        }

        let language: String
        let relevance: Double
        let tokens: [Token]
    }

    struct Fixture: CustomTestStringConvertible, Sendable {
        let language: String
        let caseName: String
        let codeURL: URL
        let tokensURL: URL

        var testDescription: String { "\(language)/\(caseName)" }
    }

    static var fixtures: [Fixture] {
        guard let root = Bundle.module.url(forResource: "Fixtures", withExtension: nil) else {
            return []
        }
        // Restrict to one language during porting: FIDELITY_LANG=cpp swift test …
        let only = ProcessInfo.processInfo.environment["FIDELITY_LANG"]
        let fm = FileManager.default
        var result: [Fixture] = []
        for langDir in (try? fm.contentsOfDirectory(at: root, includingPropertiesForKeys: nil)) ?? [] {
            guard langDir.hasDirectoryPath else { continue }
            let language = langDir.lastPathComponent
            if let only, language != only { continue }
            for file in (try? fm.contentsOfDirectory(at: langDir, includingPropertiesForKeys: nil)) ?? []
            where file.lastPathComponent.hasSuffix(".code.txt") {
                let caseName = String(file.lastPathComponent.dropLast(".code.txt".count))
                result.append(Fixture(
                    language: language,
                    caseName: caseName,
                    codeURL: file,
                    tokensURL: langDir.appendingPathComponent("\(caseName).tokens.json")
                ))
            }
        }
        return result.sorted { $0.testDescription < $1.testDescription }
    }

    @Test(arguments: fixtures)
    func matchesReference(_ fixture: Fixture) throws {
        let code = try String(contentsOf: fixture.codeURL, encoding: .utf8)
        let expected = try JSONDecoder().decode(Expected.self, from: Data(contentsOf: fixture.tokensURL))

        let result = Highlighter.shared.highlight(code, as: fixture.language, ignoreIllegals: true)

        #expect(result.language == expected.language, "language mismatch")
        #expect(abs(result.relevance - expected.relevance) < 0.001, "relevance: got \(result.relevance), expected \(expected.relevance)")

        let got = result.tokens
        let want = expected.tokens
        let ns = code as NSString

        func describe(_ start: Int, _ length: Int, _ scopes: [String]) -> String {
            let text = ns.substring(with: NSRange(location: start, length: min(length, 40)))
            return "[\(start)..+\(length)] \(scopes.joined(separator: ">")) «\(text)»"
        }

        for i in 0..<max(got.count, want.count) {
            let g = i < got.count ? got[i] : nil
            let w = i < want.count ? want[i] : nil
            if let g, let w,
               g.range.location == w.start, g.range.length == w.length, g.scopes == w.scopes {
                continue
            }
            Issue.record("""
            token #\(i) differs:
              got:      \(g.map { describe($0.range.location, $0.range.length, $0.scopes) } ?? "∅")
              expected: \(w.map { describe($0.start, $0.length, $0.scopes) } ?? "∅")
            """)
            break
        }
        #expect(got.count == want.count, "token count: got \(got.count), expected \(want.count)")
    }
}
